'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.RANKS = exports.XP_CONFIG = exports.GAME_CONSTANTS = exports.WEAPON_CONFIGS = void 0;
const types_1 = require('./types');
exports.WEAPON_CONFIGS = {
  [types_1.WeaponType.ASSAULT_RIFLE]: {
    type: types_1.WeaponType.ASSAULT_RIFLE,
    name: 'M4A1',
    damage: 30,
    headshotMultiplier: 2.0,
    fireRate: 600,
    magazineSize: 30,
    reserveAmmo: 90,
    reloadTime: 2000,
    spread: 0.05,
    recoil: 0.1,
    range: 100,
  },
  [types_1.WeaponType.SMG]: {
    type: types_1.WeaponType.SMG,
    name: 'MP5',
    damage: 22,
    headshotMultiplier: 1.8,
    fireRate: 800,
    magazineSize: 30,
    reserveAmmo: 90,
    reloadTime: 1800,
    spread: 0.08,
    recoil: 0.08,
    range: 50,
  },
  [types_1.WeaponType.SHOTGUN]: {
    type: types_1.WeaponType.SHOTGUN,
    name: 'M870',
    damage: 80,
    headshotMultiplier: 1.5,
    fireRate: 60,
    magazineSize: 8,
    reserveAmmo: 32,
    reloadTime: 3000,
    spread: 0.3,
    recoil: 0.3,
    range: 20,
  },
  [types_1.WeaponType.SNIPER]: {
    type: types_1.WeaponType.SNIPER,
    name: 'AWP',
    damage: 100,
    headshotMultiplier: 3.0,
    fireRate: 40,
    magazineSize: 5,
    reserveAmmo: 20,
    reloadTime: 2500,
    spread: 0.02,
    recoil: 0.4,
    range: 200,
  },
  [types_1.WeaponType.PISTOL]: {
    type: types_1.WeaponType.PISTOL,
    name: 'Glock',
    damage: 20,
    headshotMultiplier: 2.0,
    fireRate: 300,
    magazineSize: 17,
    reserveAmmo: 51,
    reloadTime: 1500,
    spread: 0.06,
    recoil: 0.05,
    range: 40,
  },
};
exports.GAME_CONSTANTS = {
  TICK_RATE: 60,
  MAX_PLAYERS_PER_MATCH: 10,
  RESPAWN_TIME: 5000,
  MATCH_TIME_LIMIT: 600,
  TEAM_DEATHMATCH_SCORE_LIMIT: 50,
  PLAYER_SPEED: 5,
  PLAYER_SPRINT_MULTIPLIER: 1.5,
  PLAYER_JUMP_FORCE: 8,
  PLAYER_GRAVITY: -20,
  PLAYER_HEIGHT: 1.8,
  PLAYER_RADIUS: 0.5,
  MAX_HEALTH: 100,
  MAX_ARMOR: 100,
};
exports.XP_CONFIG = {
  KILL: 100,
  ASSIST: 50,
  HEADSHOT_BONUS: 25,
  WIN_BONUS: 500,
  MATCH_COMPLETION: 100,
  PER_MINUTE_PLAYED: 10,
  LEVEL_UP_BASE: 1000,
  LEVEL_UP_MULTIPLIER: 1.2,
};
exports.RANKS = [
  { name: 'Bronze', minMMR: 0 },
  { name: 'Silver', minMMR: 1200 },
  { name: 'Gold', minMMR: 1500 },
  { name: 'Platinum', minMMR: 1800 },
  { name: 'Diamond', minMMR: 2100 },
  { name: 'Master', minMMR: 2500 },
  { name: 'Grandmaster', minMMR: 3000 },
];
//# sourceMappingURL=constants.js.map
